/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import modeloConection.ConexaoBD;
import modeloDao.DaoMedico;
import modeloBeans.BeansMedico;

/**
 *
 * @author Carlinhos
 */
public class FormMedicos extends javax.swing.JFrame {

    BeansMedico mod = new BeansMedico();
    DaoMedico control = new DaoMedico();
    ConexaoBD conex = new ConexaoBD();
    
    public FormMedicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelCRM = new javax.swing.JLabel();
        jLabelEspecialidade = new javax.swing.JLabel();
        jTextFieldCRM = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jComboBoxEspecialidade = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMedicos = new javax.swing.JTable();
        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jLabelCadMedicos = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabelNome.setText("Nome:");
        jPanel1.add(jLabelNome);
        jLabelNome.setBounds(20, 40, 60, 14);

        jLabelCRM.setText("CRM:");
        jPanel1.add(jLabelCRM);
        jLabelCRM.setBounds(20, 70, 60, 14);

        jLabelEspecialidade.setText("Especialidade:");
        jPanel1.add(jLabelEspecialidade);
        jLabelEspecialidade.setBounds(250, 40, 120, 14);

        jTextFieldCRM.setEnabled(false);
        jPanel1.add(jTextFieldCRM);
        jTextFieldCRM.setBounds(60, 70, 180, 30);

        jTextFieldNome.setEnabled(false);
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(60, 30, 180, 30);

        jComboBoxEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cirurgia", "Ultrassom", " " }));
        jComboBoxEspecialidade.setEnabled(false);
        jPanel1.add(jComboBoxEspecialidade);
        jComboBoxEspecialidade.setBounds(340, 30, 120, 30);

        jTableMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableMedicos);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 210, 452, 110);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(190, 170, 90, 30);
        jPanel1.add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(10, 170, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 50, 470, 340);

        jLabelCadMedicos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCadMedicos.setText("Cadastro de médicos:");
        getContentPane().add(jLabelCadMedicos);
        jLabelCadMedicos.setBounds(20, 10, 230, 30);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(500, 50, 80, 23);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(500, 80, 80, 23);

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(500, 110, 80, 23);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(500, 140, 80, 23);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(500, 170, 80, 23);

        setSize(new java.awt.Dimension(607, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        mod.setNome(jTextFieldNome.getText());
        mod.setEspecialidade((String) jComboBoxEspecialidade.getSelectedItem());
        mod.setCrm(Integer.parseInt(jTextFieldCRM.getText()));
        control.salvar(mod);
        jTextFieldNome.setText("");
        jTextFieldCRM.setText("");
        jTextFieldNome.setEnabled(false);
        jTextFieldCRM.setEnabled(false);
        jComboBoxEspecialidade.setEnabled(false);
        jButtonSalvar.setEnabled(false);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        jTextFieldNome.setEnabled(true);
        jTextFieldCRM.setEnabled(true);
        jComboBoxEspecialidade.setEnabled(true);
        jButtonSalvar.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
       mod.setPesquisa(jTextFieldPesquisar.getText());
       BeansMedico model = control.buscaMedico(mod);
       jTextFieldNome.setText(model.getNome());
       jTextFieldCRM.setText(String.valueOf(model.getCrm()));    //valueOf transforma Int em String
       jComboBoxEspecialidade.setSelectedItem(model.getEspecialidade());  
       jButtonEditar.setEnabled(true);
       jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMedicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxEspecialidade;
    private javax.swing.JLabel jLabelCRM;
    private javax.swing.JLabel jLabelCadMedicos;
    private javax.swing.JLabel jLabelEspecialidade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMedicos;
    private javax.swing.JTextField jTextFieldCRM;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
